#-----------------------------------------------------#
#   _ _  ___       ___  ___  ___   _  ___  ___  ___   #
#  | | || . \ ___ | . \| . \| . | | || __>|  _>|_ _|  #
#  |   ||  _/|___||  _/|   /| | |_| || _> | <__ | |   #
#  |_|_||_|       |_|  |_\_\`___'\__/|___>`___/ |_|   #
#                                                     #
#-----------------------------------------------------#

#---------# You can decide if you want to verify the new versions of the plugin,
# UPDATES # The checks are made when the server starts.
#---------# Note: that these messages can only be seen by players with op rank.
updates: true

#-----------------# If activated, the groups and commands defined in the groups.yml file are activated.
# LOCKED COMMANDS # If disabled, the commands will work as usual, there will be no control.
#-----------------# Note: players with op rank, by default do not need any groups, will have access to all commands.
locked-commands: true

#-----------------# Here is the warning message the player receives when he tries to rummage through your commands.
# WARNING MESSAGE # Please note that this message is received by the player in title format on their screen,
#-----------------# So you must configure a title and subtitle.

# Note: All messages in this addon support color codes, to know more about them: https://minecraft.gamepedia.com/Formatting_codes
# Please do not use §, just use & + the color identifier, to avoid mistakes.
warning-message:
    title: '&e&k2&r&l(ﾉ◕ヮ◕)ﾉ*:･ﾟ &c&lError 404&r&e&k2'
    subtitle: '&cYou are not allowed to use that command, contact staff if this is a mistake.'

#----------# This is the time the player will have to wait to use another command.
# COOLDOWN # This cooldown is only activated if the player uses a command which is not allowed.
#----------# Note: Set the time in seconds, the plugin will take care of the rest.
cooldown:
    time: 6
    message: "&cYou can't use another command for &f%timeRemaining% &cseconds."

#--------# These are the sounds that will be emitted next to the warning message to the player.
# SOUNDS # Note: The plugin randomly chooses which sound to play to the player,
#--------# based on the list below.
sounds:
    enable: true
    list:
        - 'AMBIENT_CAVE'
        - 'ENTITY_ENDER_DRAGON_DEATH'
        - 'ENTITY_ENDERMAN_DEATH'
        - 'MUSIC_UNDER_WATER'