#-------------------------------------------------------------------------------------------------------#
# :::    ::: :::::::::   :::::::::  :::::::::   ::::::::  ::::::::::: ::::::::::  ::::::::  ::::::::::: #
# :+:    :+: :+:    :+:  :+:    :+: :+:    :+: :+:    :+:     :+:     :+:        :+:    :+:     :+:     #
# +:+    +:+ +:+    +:+  +:+    +:+ +:+    +:+ +:+    +:+     +:+     +:+        +:+            +:+     #
# +#++:++#++ +#++:++#+   +#++:++#+  +#++:++#:  +#+    +:+     +#+     +#++:++#   +#+            +#+     #
# +#+    +#+ +#+         +#+        +#+    +#+ +#+    +#+     +#+     +#+        +#+            +#+     #
# #+#    #+# #+#         #+#        #+#    #+# #+#    #+# #+# #+#     #+#        #+#    #+#     #+#     #
# ###    ### ###         ###        ###    ###  ########   #####      ##########  ########      ###     #
#-------------------------------------------------------------------------------------------------------#

updates: true

locked-commands: true

tab-usage-permission: 'hidepluginsproject.tabusage'

bypass-permission: 'hidepluginsproject.bypass'

player-command-history: true

prefix:
  enable: true
  prefix: "&a&lHPP&7&l>&r"

warning-message:
  title:
    enable: true
    top: "&e&k2&r&l(ﾉ◕ヮ◕)ﾉ*:･ﾟ &c&lError 404&r&e&k2"
    bottom: "&cYou are not allowed to use that command, contact staff if this is a mistake."
  message:
    enable: true
    lines:
      - '&e&k2&r&l(ﾉ◕ヮ◕)ﾉ*:･ﾟ &c&lError 404&r&e&k2'
      - '&cYou are not allowed to use that command, contact staff if this is a mistake.'

potion-effect:
  enable: true
  effect: 'BLINDNESS'
  time: 6
  amplifier: 1

particles:
  enable: true
  particle: 'MOB_APPEARANCE'
  amount: 2

cooldown:
  enable: true
  message: "&cYou can't use another command for &f%time% &cseconds."
  time: 6

sounds:
  enable: true
  list:
    - 'AMBIENT_CAVE'
    - 'ENTITY_ELDER_GUARDIAN_CURSE'