updates: true
news-broadcast: true
language: 'english'

locked-commands: true
warning-message:
    title: '&e&k2&r&l(ﾉ◕ヮ◕)ﾉ*:･ﾟ &c&lError 404&r&e&k2'
    subtitle: '&cYou are not allowed to use that command, contact staff if this is a mistake.'
sounds:
    enable: true
    .:
        - '<sound...>'
        - '<sound...>'
        - '<sound...>'
        - '<sound...>'