#-----------------------------------------------------#
#   _ _  ___       ___  ___  ___   _  ___  ___  ___   #
#  | | || . \ ___ | . \| . \| . | | || __>|  _>|_ _|  #
#  |   ||  _/|___||  _/|   /| | |_| || _> | <__ | |   #
#  |_|_||_|       |_|  |_\_\`___'\__/|___>`___/ |_|   #
#                                                     #
#-----------------------------------------------------#

#---------# You can decide if you want to verify the new versions of the plugin,
# UPDATES # The checks are made when the server starts.
#---------# Note: that these messages can only be seen by players with op rank.
updates: true

#-----------------# If activated, the groups and commands defined in the groups.yml file are activated.
# LOCKED COMMANDS # If disabled, the commands will work as usual, there will be no control.
#-----------------# Note: players with op rank, by default do not need any groups, will have access to all commands.
locked-commands: true

#-----------------# Here is the warning message the player receives when he tries to rummage through your commands.
# WARNING MESSAGE # Note that the message the player receives depends on how you configure it.
#-----------------# By default it will appear in title format

# Note: All messages in this addon support color codes, to know more about them: https://minecraft.gamepedia.com/Formatting_codes
# Please do not use §, just use & + the color identifier, to avoid mistakes.
warning-message:
    enable: true
    type: 'screen-title'
    screen-title:
        title: '&e&k2&r&l(ﾉ◕ヮ◕)ﾉ*:･ﾟ &c&lError 404&r&e&k2'
        subtitle: '&cYou are not allowed to use that command, contact staff if this is a mistake.'
    chat-message:
        - '&e&k2&r&l(ﾉ◕ヮ◕)ﾉ*:･ﾟ &c&lError 404&r&e&k2'
        - '&cYou are not allowed to use that command, contact staff if this is a mistake.'

#---------------# Specify here the effect that accompanies the warning message, you can check the effects in the following link:
# POTION EFFECT # https://minecraft-helpandinfo.weebly.com/potion-effects-ids.html - Write the name of the effect all in uppercase.
#---------------# Note: Set the time in seconds, the plugin will take care of the rest.
potion-effect:
    enable: true
    effect: 'BLINDNESS'
    time: 6
    amplifier: 1

#-----------# Specify here the particle that accompanies the warning message, you can see the types of particles in the following link:
# PARTICLES # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
#-----------# Note: Write the name of the effect all in uppercase.
particles:
    enable: true
    particle: 'SMOKE_LARGE'

#----------# This is the time the player will have to wait to use another command.
# COOLDOWN # This cooldown is only activated if the player uses a command which is not allowed.
#----------# Note: Set the time in seconds, the plugin will take care of the rest.
cooldown:
    enable: true
    message: "&cYou can't use another command for &f%timeRemaining% &cseconds."
    time: 6

#--------# These are the sounds that will be emitted next to the warning message to the player.
# SOUNDS # Note: The plugin randomly chooses which sound to play to the player,
#--------# based on the list below.

# 1.12.2: https://jd.andross.fr/spigot-1.12.2-R0.1-SNAPSHOT/javadoc/org/bukkit/Sound.html
# 1.13.2: https://jd.andross.fr/spigot-1.13.2-R0.1-SNAPSHOT/javadoc/org/bukkit/Sound.html
# 1.14.4: https://jd.andross.fr/spigot-1.14.4-R0.1-SNAPSHOT/javadoc/org/bukkit/Sound.html
# 1.15.2: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sounds:
    enable: true
    list:
        - 'AMBIENT_CAVE'