updates: true

language: 'english'

locked-commands: true

player-command-history: true

prefix:
  enable: true
  prefix: "§a§lHPP§7§l>§r"

warning-message:
  enable: true
  type: 'screen-title'
  screen-title:
    title: "&e&k2&r&l(ﾉ◕ヮ◕)ﾉ*:･ﾟ &c&lError 404&r&e&k2"
    subtitle: "&cYou are not allowed to use that command, contact staff if this is a mistake."
  chat-message:
    - '&e&k2&r&l(ﾉ◕ヮ◕)ﾉ*:･ﾟ &c&lError 404&r&e&k2'
    - '&cYou are not allowed to use that command, contact staff if this is a mistake.'

potion-effect:
  enable: true
  effect: 'BLINDNESS'
  time: 6
  amplifier: 1

particles:
  enable: true
  particle: 'SMOKE_LARGE'

cooldown:
  enable: false
  message: "&cYou can't use another command for &f%time% &cseconds."
  time: 6

custom-commands:
  /test:
    description: test
    usageMessage: /test
    aliases:
      - 't'

sounds:
  enable: true
  list:
    - 'AMBIENT_CAVE'