name: HidePlugins_Project
author: ComplexCode
version: 2.8.1
api-version: 1.13
main: io.github.complexcodegit.hidepluginsproject.HidePluginsProject
description: HidePlugins Project is perfect to hide all your plugins!
commands:
  hproject:
    description: Main command of the plugin.
    aliases: hp